services:
  origin:
    build: ./origin
    ports:
      - "9000:9000"
    networks:
      cdn:
        ipv4_address: 192.168.0.10

  edge1:
    hostname: edge1
    build: 
      context: ./edge
    environment:
      EDGE_NUMBER: 1

    ports:
      - "5001:5000"
    networks:
      cdn:
        ipv4_address: 192.168.0.51

  edge2:
    hostname: edge2
    build:
      context: ./edge
    environment:
      EDGE_NUMBER: 2
    ports:
      - "5002:5000"
    networks:
      cdn:
        ipv4_address: 192.168.0.52

networks:
  cdn:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24

